Add missing header files for source distribution
We were not listing all of the uapi header files in ethtool_SOURCES
which prevented the proper construction of a distribution source
tarball. This is noticeable with older kernel headers where the build
would be breaking in such a way:

/storage/buildroot/output/arm64/host/bin/aarch64-linux-gcc
-DHAVE_CONFIG_H -I.  -I./uapi  -D_LARGEFILE_SOURCE
-D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Wextra
-D_POSIX_C_SOURCE=200809L -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
-D_FILE_OFFSET_BITS=64  -Os -g0 -D_FORTIFY_SOURCE=2 -std=gnu11 -c -o
netlink/rings.o netlink/rings.c
In file included from internal.h:45,
                  from common.c:7:
./uapi/linux/ethtool.h:1507:19: warning: implicit declaration of
function '__KERNEL_DIV_ROUND_UP' [-Wimplicit-function-declaration]
   __u32 queue_mask[__KERNEL_DIV_ROUND_UP(MAX_NUM_QUEUE, 32)];
                    ^~~~~~~~~~~~~~~~~~~~~
./uapi/linux/ethtool.h:1507:8: error: variably modified 'queue_mask'
at file scope
   __u32 queue_mask[__KERNEL_DIV_ROUND_UP(MAX_NUM_QUEUE, 32)];
         ^~~~~~~~~~
make[3]: *** [Makefile:1410: common.o] Error 1
make[3]: *** Waiting for unfinished jobs....

Fixes: da2beb7afc25 ("update UAPI header copies")
Reported-by: Markus Mayer <mmayer@broadcom.com>
Signed-off-by: Florian Fainelli <florian.fainelli@broadcom.com>